'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class User

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSearch As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''ddlRoles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlRoles As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''ddlSearchType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlSearchType As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''dnngridUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dnngridUsers As Global.DotNetNuke.Web.UI.WebControls.DnnGrid
    End Class
End Namespace
