'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Forum
    Partial Public Class ModuleSettings
        Protected WithEvents plGroup As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents cboGroup As System.Web.UI.WebControls.DropDownList
        Protected WithEvents rowDefaultForum As System.Web.UI.HtmlControls.HtmlTableRow
        Protected WithEvents plDefaultForum As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents DefaultForumTree As DotNetNuke.UI.WebControls.DnnTree
    End Class
End Namespace
