'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum

	Partial Public Class ContentRemoved

		'''<summary>
		'''litCSSLoad control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litCSSLoad As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''imgHeadSpacer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgHeadSpacer As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblTitleContentRemoved control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitleContentRemoved As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgHeadSpacer2 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgHeadSpacer2 As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblContentRemoved control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblContentRemoved As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgFootSpacer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgFootSpacer As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''imgFootSpacer2 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgFootSpacer2 As Global.System.Web.UI.WebControls.Image
	End Class
End Namespace
