'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum

	Partial Public Class SearchPage

		'''<summary>
		'''plPostDates control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plPostDates As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lblStartDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rdpFrom control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rdpFrom As Global.Telerik.Web.UI.RadDatePicker

		'''<summary>
		'''lblEndDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rdpTo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rdpTo As Global.Telerik.Web.UI.RadDatePicker

		'''<summary>
		'''plUserSuggest control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserSuggest As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtForumUserSuggest control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtForumUserSuggest As Global.DotNetNuke.UI.WebControls.DNNTextSuggest

		'''<summary>
		'''plSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSubject As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''plBody control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plBody As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSearch control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''plThreadStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plThreadStatus As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''rcbThreadStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rcbThreadStatus As Global.Telerik.Web.UI.RadComboBox

		'''<summary>
		'''plForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plForums As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''rtvForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rtvForums As Global.Telerik.Web.UI.RadTreeView

		'''<summary>
		'''cmdSearch control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''valCompareDates control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valCompareDates As Global.System.Web.UI.WebControls.CompareValidator

		'''<summary>
		'''lblInfo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
