'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.832
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace DotNetNuke.Modules.Forum
    Partial Public Class ThreadMove
        Protected WithEvents litCSSLoad As System.Web.UI.WebControls.Literal
        Protected WithEvents pnlContainer As System.Web.UI.WebControls.Panel
        Protected WithEvents plSubject As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtSubject As System.Web.UI.WebControls.TextBox
        Protected WithEvents plOldForum As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents txtOldForum As System.Web.UI.WebControls.TextBox
        Protected WithEvents rowForum As System.Web.UI.HtmlControls.HtmlTableRow
        Protected WithEvents plNewForum As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents ForumTree As DotNetNuke.UI.WebControls.DnnTree
        Protected WithEvents lblErrorMsg As System.Web.UI.WebControls.Label
        Protected WithEvents plEmailUsers As DotNetNuke.UI.UserControls.LabelControl
        Protected WithEvents chkEmailUsers As System.Web.UI.WebControls.CheckBox
        Protected WithEvents cmdCancel As System.Web.UI.WebControls.LinkButton
        Protected WithEvents cmdMove As System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
