'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum

	Partial Public Class PostDelete

		'''<summary>
		'''litCSSLoad control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litCSSLoad As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''pnlContainer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''plDeleteTemplate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plDeleteTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''ddlDeleteTemplate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlDeleteTemplate As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''plReason control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plReason As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtReason control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtReason As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valEmailedResponse control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valEmailedResponse As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''rowEmailUsers control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEmailUsers As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEmailUser control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailUser As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEmailUsers control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEmailUsers As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''imgSpacerL control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSpacerL As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgSpacerR control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSpacerR As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblAuthor control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblMessage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdDelete control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
