'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum

	Partial Public Class SearchPage

		'''<summary>
		'''litCSSLoad control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litCSSLoad As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''plPostDates control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plPostDates As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lblStartDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblStartDate As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtFromDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtFromDate As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''cmdCalFrom control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCalFrom As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''lblEndDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblEndDate As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtToDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtToDate As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''cmdCalTo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCalTo As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''valStartDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valStartDate As Global.System.Web.UI.WebControls.CompareValidator

		'''<summary>
		'''valEndDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valEndDate As Global.System.Web.UI.WebControls.CompareValidator

		'''<summary>
		'''valDates control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valDates As Global.System.Web.UI.WebControls.CompareValidator

		'''<summary>
		'''plUserSuggest control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserSuggest As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtForumUserSuggest control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtForumUserSuggest As Global.DotNetNuke.UI.WebControls.DNNTextSuggest

		'''<summary>
		'''plSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSubject As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''plBody control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plBody As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSearch control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSearch As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''plThreadStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plThreadStatus As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''ddlThreadStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlThreadStatus As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''plForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plForums As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''ForumTree control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ForumTree As Global.DotNetNuke.UI.WebControls.DnnTree

		'''<summary>
		'''lblInfo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''cmdSearch control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdSearch As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
