'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum

	Partial Public Class PMAdd

		'''<summary>
		'''litCSSLoad control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litCSSLoad As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''pnlContainer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''imgLeftCap control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgLeftCap As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''imgHeader control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgHeader As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblHeader control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgRightCap control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgRightCap As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''rowOldPost control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowOldPost As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plAuthor control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plAuthor As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''hlAuthor control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents hlAuthor As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''plOriginalMessage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plOriginalMessage As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lblMessage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowNewPost control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowNewPost As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plRecipient control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plRecipient As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtForumUserSuggest control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtForumUserSuggest As Global.DotNetNuke.UI.WebControls.DNNTextSuggest

		'''<summary>
		'''rowSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowSubject As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSubject As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''teContent control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents teContent As Global.DotNetNuke.UI.UserControls.TextEditor

		'''<summary>
		'''rowPreview control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowPreview As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblPreview control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPreview As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblInfo control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''cmdSubmit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdPreview control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdPreview As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdBackToEdit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdBackToEdit As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
