'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum

	Partial Public Class PublicProfile

		'''<summary>
		'''litCSSLoad control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litCSSLoad As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''imgSpc1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSpc1 As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblProfile control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblProfile As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgSpc2 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSpc2 As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblAlias control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblAlias As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtAlias control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtAlias As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowPMUser control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowPMUser As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblPMUser control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPMUser As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''cmdPMUser control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdPMUser As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''litEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litEmail As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''rowUserWeb control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserWeb As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblURL control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblURL As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lnkWWW control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lnkWWW As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''lblIM control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblIM As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtIM control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtIM As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowStats control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowStats As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblStat control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblStat As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblStatistic control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblStatistic As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblJoinedDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblJoinedDate As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblPCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblPostCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPostCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowPostLink control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowPostLink As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblViewPost control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblViewPost As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lnkUserPosts control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lnkUserPosts As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''rowUserSignature control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserSignature As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblSig control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblSig As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblSignature control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblSignature As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowRanking control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowRanking As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblRanking control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblRanking As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgRanking control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgRanking As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''lblRankTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblRankTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowUserAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserAvatar As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblAvatar As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgAvatar As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''rowSystemAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowSystemAvatar As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''lblSystemAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblSystemAvatar As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgSystemAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSystemAvatar As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''dshBiography control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dshBiography As Global.DotNetNuke.UI.UserControls.SectionHeadControl

		'''<summary>
		'''tblBiography control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblBiography As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''litBiography control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litBiography As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''rowModeratorAdmin control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowModeratorAdmin As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''dshModeratorSettings control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dshModeratorSettings As Global.DotNetNuke.UI.UserControls.SectionHeadControl

		'''<summary>
		'''tblModerator control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblModerator As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''plIsTrusted control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plIsTrusted As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkIsTrusted control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkIsTrusted As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEditUserSig control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEditUserSig As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEditUserSig control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEditUserSig As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSignature control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSignature As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''rowModifyUserAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowModifyUserAvatar As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plAvatar As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''ctlUserAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ctlUserAvatar As Global.DotNetNuke.Modules.Forum.AvatarControl

		'''<summary>
		'''rowUserBanning control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserBanning As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plUserBanned control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserBanned As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkUserBanned control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkUserBanned As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''lblLiftBan control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblLiftBan As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''imgSpc3 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSpc3 As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''imgSpc4 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgSpc4 As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''rowFooter control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowFooter As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdManageUser control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdManageUser As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
