'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum

	Partial Public Class UCPLoader

		'''<summary>
		'''litCSSLoad control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litCSSLoad As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''pnlContainer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''UCPmenu control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents UCPmenu As Global.DotNetNuke.Modules.Forum.UCP.Menu

		'''<summary>
		'''phUserControl control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents phUserControl As Global.System.Web.UI.WebControls.PlaceHolder

		'''<summary>
		'''cmdHome control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdHome As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
