'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class Community

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divUserOnline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUserOnline As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plUserOnline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserOnline As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUserOnline control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUserOnline As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEnableExtProfile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnableExtProfile As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableExtProfilePage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableExtProfilePage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableExtProfilePage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableExtProfilePage As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divExtProfilePageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divExtProfilePageID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plExtProfilePageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExtProfilePageID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbExtProfilePageID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbExtProfilePageID As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divExtProfileUserParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divExtProfileUserParam As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plExtProfileUserParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExtProfileUserParam As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExtProfileUserParam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExtProfileUserParam As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divExtProfileParamName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divExtProfileParamName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plExtProfileParamName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExtProfileParamName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExtProfileParamName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExtProfileParamName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divExtProfileParamValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divExtProfileParamValue As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plExtProfileParamValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plExtProfileParamValue As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtExtProfileParamValue control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExtProfileParamValue As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
