'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

	Partial Public Class Email

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plAutomatedAddress control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plAutomatedAddress As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtAutomatedAddress control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtAutomatedAddress As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valAddy control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valAddy As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''valEmailAddy control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valEmailAddy As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''plEmailAddressDisplayName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailAddressDisplayName As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtEmailAddressDisplayName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtEmailAddressDisplayName As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valDisplay control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valDisplay As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''plNofify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plNofify As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkNotify As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEnablePerForumFrom control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEnablePerForumFrom As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnablePerForumFrom control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnablePerForumFrom As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnablePerForumFrom control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnablePerForumFrom As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEnableEditEmails control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEnableEditEmails As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnableEditEmails control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableEditEmails As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableEditEmails control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableEditEmails As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEmailQueueTask control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEmailQueueTask As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEmailQueueTask control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailQueueTask As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEmailQueueTask control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEmailQueueTask As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEnableListServer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEnableListServer As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnableListServer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableListServer As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableListServer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableListServer As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowListServerFolder control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowListServerFolder As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plListServerFolder control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plListServerFolder As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtListServerFolder control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtListServerFolder As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
