'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class Attachment

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAttachment As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAttachment As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAttachment control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAttachment As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divAnonDownloads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAnonDownloads As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAnonDownloads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAnonDownloads As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAnonDownloads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAnonDownloads As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divAttachmentPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAttachmentPath As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAttachmentPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAttachmentPath As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAttachmentPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAttachmentPath As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAttachmentPath control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAttachmentPath As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''divMaxAttachmentSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divMaxAttachmentSize As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plMaxAttachmentSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plMaxAttachmentSize As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtMaxAttachmentSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtMaxAttachmentSize As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valMaxAttachSize control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valMaxAttachSize As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
