'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class ForumEdit

        '''<summary>
        '''ACPmenu control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ACPmenu As Global.DotNetNuke.Modules.Forum.ACP.Menu

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rtsForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtsForum As Global.Telerik.Web.UI.RadTabStrip

        '''<summary>
        '''rmpForumSettings control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rmpForumSettings As Global.DotNetNuke.Web.UI.WebControls.DnnMultiPage

        '''<summary>
        '''rpvGeneral control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvGeneral As Global.DotNetNuke.Web.UI.WebControls.DnnPageView

        '''<summary>
        '''divForumID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divForumID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plForumID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumID As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtForumID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plEnableForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForum As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkActive control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkActive As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plGroupName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plGroupName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbGroup control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbGroup As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divParentForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divParentForum As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plParentForumName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plParentForumName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbParentForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbParentForum As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plForumName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtForumName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valName As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plForumDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumDescription As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtForumDescription control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumDescription As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plForumCreatorName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumCreatorName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtForumCreatorName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtForumCreatorName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plCreatedDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtCreatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtCreatedDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plUpdatedName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUpdatedName As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtUpdatedName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUpdatedName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plUpdatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUpdatedDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtUpdatedDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtUpdatedDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''rpvOptions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvOptions As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''plForumType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumType As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbForumType control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbForumType As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divForumBehavior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divForumBehavior As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plForumBehavior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumBehavior As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbForumBehavior control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbForumBehavior As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divForumLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divForumLink As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plForumLink control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumLink As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ctlURL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlURL As Global.DotNetNuke.UI.UserControls.UrlControl

        '''<summary>
        '''divLinkTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divLinkTracking As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''ctlTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ctlTracking As Global.DotNetNuke.UI.UserControls.URLTrackingControl

        '''<summary>
        '''divPolls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPolls As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAllowPolls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAllowPolls As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAllowPolls control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAllowPolls As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divThreadStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableForumsThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForumsThreadStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableForumsThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableForumsThreadStatus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divRating As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableForumsRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForumsRating As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableForumsRating control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableForumsRating As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnableRSS As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableRSS As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableRSS control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableRSS As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEnableSitemap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnableSitemap As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableSitemap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableSitemap As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableSitemap control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableSitemap As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divSitemapPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSitemapPriority As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plSitemapPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSitemapPriority As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''textSitemapPriority control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents textSitemapPriority As Global.DotNetNuke.Web.UI.WebControls.DnnNumericTextBox

        '''<summary>
        '''divPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPermissions As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''dgPermissions control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgPermissions As Global.DotNetNuke.Modules.Forum.Controls.ForumPermissionsGrid

        '''<summary>
        '''lblPrivateNote control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPrivateNote As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plForumPermTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForumPermTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbForumPermTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbForumPermTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''rpvEmail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvEmail As Global.Telerik.Web.UI.RadPageView

        '''<summary>
        '''plEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAddress As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailAddress control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailAddress As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAddy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAddy As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valEmailAddy control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailAddy As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plEmailFriendlyFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailFriendlyFrom As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailFriendlyFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailFriendlyFrom As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valDisplay As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''divSubscribeByDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divSubscribeByDefault As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plNotifyByDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotifyByDefault As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkNotifyByDefault control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotifyByDefault As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEmailStatusChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailStatusChange As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailStatusChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailStatusChange As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEmailStatusChange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailStatusChange As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEmailServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailServer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailServer As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailServer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailServer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailUser As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailUser As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailUser As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divEmailPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailPass As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailPass As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailPass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailPass As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divEmailPort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailPort As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailPort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailPort As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEmailPort control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEmailPort As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''divEmailSSL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailSSL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailEnableSSL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailEnableSSL As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEmailEnableSSL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailEnableSSL As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEmailAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailAuth As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailAuth As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlEmailAuth control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlEmailAuth As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''cmdAdd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAdd As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdHome control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdHome As Global.System.Web.UI.WebControls.HyperLink
    End Class
End Namespace
