'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class UserSettings

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plNameDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNameDisplay As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''rcbNameDisplay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbNameDisplay As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''divEditWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEditWindow As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plPostEditWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPostEditWindow As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtPostEditWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostEditWindow As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPostEditWindow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPostEditWindow As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''plAutoTrustEnabled control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoTrustEnabled As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableAutoTrust control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableAutoTrust As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divAutoTrustTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAutoTrustTime As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAutoTrustTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoTrustTime As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAutoTrustTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAutoTrustTime As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valAutoTrustTime control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valAutoTrustTime As Global.System.Web.UI.WebControls.RangeValidator

        '''<summary>
        '''plAutoLockTrust control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAutoLockTrust As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkAutoLockTrust control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkAutoLockTrust As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plUserReadManagement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plUserReadManagement As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkUserReadManagement control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkUserReadManagement As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEnableUserSignatures control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableUserSignatures As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableUserSignatures control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableUserSignatures As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divModSigUpdates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divModSigUpdates As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableModSigUpdates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableModSigUpdates As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableModSigUpdates control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableModSigUpdates As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divHTMLSignatures control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divHTMLSignatures As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableHTMLSignatures control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableHTMLSignatures As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableHTMLSignatures control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableHTMLSignatures As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divHideModEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divHideModEdit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plHideModEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plHideModEdit As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkHideModEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkHideModEdit As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divUserBanning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divUserBanning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableUserBanning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableUserBanning As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEnableUserBanning control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableUserBanning As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
