'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

    Partial Public Class Advertisement

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plAdsAfterFirstPost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAdsAfterFirstPost As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''cbAdsAfterFirstPost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cbAdsAfterFirstPost As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAddAdverAfterPostNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAddAdverAfterPostNo As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''tbAddAdverAfterPostNo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbAddAdverAfterPostNo As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valreqView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valreqView As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''valView control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valView As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plAdvertisementText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAdvertisementText As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''tbAdvertisementText control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbAdvertisementText As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plVendorsList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plVendorsList As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rgVendors control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rgVendors As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
