'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.UCP

    Partial Public Class Settings

        '''<summary>
        '''lblTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plEmailFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailFormat As Global.System.Web.UI.UserControl

        '''<summary>
        '''rcbEmailFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rcbEmailFormat As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''plThreadsPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThreadsPerPage As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtThreadsPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtThreadsPerPage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valThreadsPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valThreadsPerPage As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''plPostsPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPostsPerPage As Global.System.Web.UI.UserControl

        '''<summary>
        '''txtPostsPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPostsPerPage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valPostsPerPage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valPostsPerPage As Global.System.Web.UI.WebControls.RegularExpressionValidator

        '''<summary>
        '''divOnlineStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divOnlineStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plOnlineStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plOnlineStatus As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkOnlineStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkOnlineStatus As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEnableDefaultPostNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnableDefaultPostNotify As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableDefaultPostNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableDefaultPostNotify As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableDefaultPostNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableDefaultPostNotify As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divEnableSelfNotifications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEnableSelfNotifications As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableSelfNotifications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableSelfNotifications As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableSelfNotifications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableSelfNotifications As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divForumModNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divForumModNotify As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEnableForumModNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEnableForumModNotify As Global.System.Web.UI.UserControl

        '''<summary>
        '''chkEnableForumModNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEnableForumModNotify As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divClearReads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divClearReads As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plClearReads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plClearReads As Global.System.Web.UI.UserControl

        '''<summary>
        '''cmdClearReads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdClearReads As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdUpdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
