'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum

    Partial Public Class PostEdit

        '''<summary>
        '''divNewPost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNewPost As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plForum As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlForum As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plSubject As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''plBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBody As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''divAttachments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divAttachments As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plAttachments control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAttachments As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''divPinned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPinned As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plPinned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plPinned As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkIsPinned control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsPinned As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divNotify As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNotify As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkNotify control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkNotify As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divClose As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plClose control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plClose As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkIsClosed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkIsClosed As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''divThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divThreadStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plThreadStatus As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''dnncbThreadStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dnncbThreadStatus As Global.DotNetNuke.Web.UI.WebControls.DnnComboBox

        '''<summary>
        '''divTagging control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divTagging As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTerms As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''tsTerms control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tsTerms As Global.DotNetNuke.Web.UI.WebControls.TermsSelector

        '''<summary>
        '''divPoll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPoll As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tblPoll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPoll As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''imgAltHeaderPoll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAltHeaderPoll As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPostPollHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostPollHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plQuestion As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtQuestion As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''txtPollID control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtPollID As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plAnswers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAnswers As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''dgAnswers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgAnswers As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''plNewAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plNewAnswer As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtAddAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAddAnswer As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdAddAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdAddAnswer As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblNoAnswer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNoAnswer As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plTakenMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plTakenMessage As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtTakenMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtTakenMessage As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''plShowResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plShowResults As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkShowResults control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkShowResults As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEndDate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtEndDate As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''cmdCalEndDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCalEndDate As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''divPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divPreview As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tblPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPreview As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''imgPrevSpaceL control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPrevSpaceL As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''imgAltHeaderPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAltHeaderPreview As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPreviewHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreviewHead As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''imgPrevSpaceR control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgPrevSpaceR As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPreview As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divModerate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divModerate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblModerate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblModerate As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdSubmit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdSubmit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdBackToForum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBackToForum As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdBackToEdit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdBackToEdit As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdPreview control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdPreview As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''lblInfo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInfo As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''divOldPost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divOldPost As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''tblOldPost control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblOldPost As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''imgReplyLeft control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgReplyLeft As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''imgAltHeaderReply control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgAltHeaderReply As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblPostReplyHeader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblPostReplyHeader As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''hlAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hlAuthor As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''imgReplyRight control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgReplyRight As Global.System.Web.UI.WebControls.Image

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
