'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum

    Partial Public Class PostDelete

        '''<summary>
        '''lblTitleSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTitleSubject As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''lblSubject control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plDeleteTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plDeleteTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''ddlDeleteTemplate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlDeleteTemplate As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''plReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plReason As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''txtReason control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReason As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''valEmailedResponse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents valEmailedResponse As Global.System.Web.UI.WebControls.RequiredFieldValidator

        '''<summary>
        '''divEmailUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents divEmailUsers As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''plEmailUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plEmailUser As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''chkEmailUsers control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents chkEmailUsers As Global.System.Web.UI.WebControls.CheckBox

        '''<summary>
        '''plAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plAuthor As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblAuthor control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblAuthor As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''plBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents plBody As Global.DotNetNuke.UI.UserControls.LabelControl

        '''<summary>
        '''lblBody control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblBody As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''cmdDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''cmdCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
    End Class
End Namespace
