'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4016
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.ACP

	Partial Public Class Ranking

		'''<summary>
		'''lblRankTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblRankTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''tblRanks control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblRanks As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''plRankings control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plRankings As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkRankings control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkRankings As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''plEnableRankingImage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableRankingImage As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableRankingImage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableRankingImage As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''plFirstRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plFirstRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl1stCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl1stCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtFirstRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtFirstRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valFirst control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valFirst As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val1st control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val1st As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl1stTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl1stTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt1stTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt1stTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img1stRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img1stRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plSecondRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSecondRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl2ndCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl2ndCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtSecondRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSecondRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val2ndRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val2ndRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val2nd control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val2nd As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl2ndTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl2ndTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt2ndTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt2ndTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img2ndRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img2ndRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plThirdRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plThirdRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl3rdCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl3rdCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtThirdRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtThirdRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val3rdRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val3rdRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val3rd control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val3rd As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl3rdTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl3rdTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt3rdTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt3rdTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img3rdRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img3rdRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plFourthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plFourthRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl4thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl4thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtFourthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtFourthRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val4thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val4thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val4th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val4th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl4thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl4thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt4thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt4thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img4thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img4thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plFifthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plFifthRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl5thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl5thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtFifthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtFifthRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val5thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val5thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val5th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val5th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl5thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl5thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt5thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt5thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img5thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img5thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plSixthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSixthRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl6thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl6thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtSixthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSixthRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val6thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val6thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val6th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val6th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl6thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl6thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt6thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt6thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img6thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img6thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plSeventhRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSeventhRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl7thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl7thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtSeventhRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSeventhRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val7thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val7thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val7th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val7th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl7thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl7thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt7thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt7thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img7thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img7thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plEigthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEigthRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl8thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl8thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtEigthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtEigthRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val8thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val8thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val8th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val8th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl8thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl8thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt8thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt8thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img8thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img8thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plNinthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plNinthRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl9thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl9thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtNinthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtNinthRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val9thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val9thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val9th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val9th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl9thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl9thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt9thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt9thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img9thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img9thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plTenthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plTenthRank As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lbl10thCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl10thCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtTenthRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtTenthRank As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''val10thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val10thRank As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''val10th control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents val10th As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''lbl10thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lbl10thTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txt10thTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt10thTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img10thRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img10thRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''plNoRanking control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plNoRanking As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lblNoCount control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblNoCount As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtNoRanking control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtNoRanking As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''lblNoTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblNoTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtNoRankTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtNoRankTitle As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''imgNoRank control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents imgNoRank As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
