'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.ACP

	Partial Public Class EmailTemplate

		'''<summary>
		'''ACPmenu control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ACPmenu As Global.DotNetNuke.Modules.Forum.ACP.Menu

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowDefaults control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowDefaults As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plDefaults control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plDefaults As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''rblstDefaults control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rblstDefaults As Global.System.Web.UI.WebControls.RadioButtonList

		'''<summary>
		'''plEmailTemplate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailTemplate As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''ddlEmailTemplate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlEmailTemplate As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''plEmailSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailSubject As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtEmailSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtEmailSubject As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valSubject control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valSubject As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''plEmailHTMLBody control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailHTMLBody As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''teContent control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents teContent As Global.DotNetNuke.UI.UserControls.TextEditor

		'''<summary>
		'''plEmailTextBody control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailTextBody As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtEmailTextBody control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtEmailTextBody As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''plAvailableKeywords control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plAvailableKeywords As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''dlKeywords control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dlKeywords As Global.System.Web.UI.WebControls.DataList

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''cmdHome control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdHome As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
