'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.ACP

	Partial Public Class Avatar

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''tblGeneral control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblGeneral As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''plEnableUserAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableUserAvatar As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableUserAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableUserAvatar As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowUserAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserAvatarPath As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plUserAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserAvatarPath As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtUserAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtUserAvatarPath As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valUsrPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valUsrPath As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''rowUserAvatarDimentions control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserAvatarDimentions As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plUserAvatarDimensions control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserAvatarDimensions As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtUserAvatarWidth control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtUserAvatarWidth As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valUsrAvW control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valUsrAvW As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''lblx1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblx1 As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''txtUserAvatarHeight control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtUserAvatarHeight As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valUsrH control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valUsrH As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''rowUserAvatarSizeLimit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserAvatarSizeLimit As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plUserAvatarSizeLimit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserAvatarSizeLimit As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtUserAvatarSizeLimit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtUserAvatarSizeLimit As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valUsrSize control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valUsrSize As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''plEnableUserAvatarPool control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableUserAvatarPool As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableUserAvatarPool control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableUserAvatarPool As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowUserAvatarPoolPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserAvatarPoolPath As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plUserAvatarPoolPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserAvatarPoolPath As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtUserAvatarPoolPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtUserAvatarPoolPath As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valUserAvatarPoolPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valUserAvatarPoolPath As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''plEnableSystemAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableSystemAvatar As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableSystemAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableSystemAvatar As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowSystemAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowSystemAvatarPath As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plSystemAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSystemAvatarPath As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSystemAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSystemAvatarPath As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valSysPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valSysPath As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''plEnableRoleAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableRoleAvatar As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableRoleAvatar control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableRoleAvatar As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowRoleAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowRoleAvatarPath As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plRoleAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plRoleAvatarPath As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtRoleAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtRoleAvatarPath As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valRoleAvatarPath control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valRoleAvatarPath As Global.System.Web.UI.WebControls.RequiredFieldValidator

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''validUserDimWidth control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents validUserDimWidth As Global.System.Web.UI.WebControls.CompareValidator

		'''<summary>
		'''validUserDimHeight control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents validUserDimHeight As Global.System.Web.UI.WebControls.CompareValidator

		'''<summary>
		'''validUserSize control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents validUserSize As Global.System.Web.UI.WebControls.CompareValidator
	End Class
End Namespace
