'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.ACP

	Partial Public Class Rating

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''tblRatings control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblRatings As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''plRatings control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plRatings As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkRatings control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkRatings As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''pl1stRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl1stRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt1stRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt1stRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img1stRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img1stRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl2ndRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl2ndRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt2ndRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt2ndRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img2ndRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img2ndRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl3rdRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl3rdRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt3rdRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt3rdRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img3rdRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img3rdRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl4thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl4thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt4thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt4thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img4thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img4thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl5thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl5thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt5thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt5thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img5thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img5thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl6thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl6thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt6thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt6thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img6thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img6thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl7thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl7thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt7thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt7thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img7thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img7thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl8thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl8thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt8thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt8thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img8thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img8thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl9thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl9thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt9thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt9thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img9thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img9thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''pl10thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pl10thRating As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txt10thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txt10thRating As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''img10thRating control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents img10thRating As Global.System.Web.UI.WebControls.Image

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
