'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.WebControls

	Partial Public Class AttachmentControl

		'''<summary>
		'''pnlContainer control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''tblAttachment control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblAttachment As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''rowInlineHelp control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowInlineHelp As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plInline control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plInline As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''rowInline control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowInline As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''ddlInline control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlInline As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''hypInline control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents hypInline As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''litScript control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents litScript As Global.System.Web.UI.WebControls.Literal

		'''<summary>
		'''plAttachments control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plAttachments As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lstAttachments control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lstAttachments As Global.System.Web.UI.WebControls.ListBox

		'''<summary>
		'''cmdDelete control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdDelete As Global.System.Web.UI.WebControls.ImageButton

		'''<summary>
		'''plUpload control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUpload As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''fuFile control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents fuFile As Global.System.Web.UI.WebControls.FileUpload

		'''<summary>
		'''cmdUpload control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblMessage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
