'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum

	Partial Public Class AvatarControl

		'''<summary>
		'''tblMain control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblMain As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''lblMessage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''dlAvatars control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dlAvatars As Global.System.Web.UI.WebControls.DataList

		'''<summary>
		'''trAvatarPool control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents trAvatarPool As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''cmdBrowsePool control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdBrowsePool As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''trFileUpload control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents trFileUpload As Global.System.Web.UI.HtmlControls.HtmlTableCell

		'''<summary>
		'''fuFile control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents fuFile As Global.System.Web.UI.WebControls.FileUpload

		'''<summary>
		'''cmdUpload control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''tblAvatarPool control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblAvatarPool As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''lblPoolHeader control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblPoolHeader As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''dlAvatarPool control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dlAvatarPool As Global.System.Web.UI.WebControls.DataList

		'''<summary>
		'''BottomPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents BottomPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''cmdCancel control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCancel As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
