'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1434
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.WebControls

    Partial Public Class EmoticonControl

        '''<summary>
        '''pnlContainer control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents pnlContainer As Global.System.Web.UI.WebControls.Panel

        '''<summary>
        '''tblAdmin control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblAdmin As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''litDisplayEmoticon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litDisplayEmoticon As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''cboFiles control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cboFiles As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''fuFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents fuFile As Global.System.Web.UI.WebControls.FileUpload

        '''<summary>
        '''cmdUpload control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmdUpload As Global.System.Web.UI.WebControls.LinkButton

        '''<summary>
        '''tblUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblUser As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''litJavaScript control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litJavaScript As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''lstEmoticon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lstEmoticon As Global.System.Web.UI.WebControls.DataList

        '''<summary>
        '''hypShowAll control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents hypShowAll As Global.System.Web.UI.WebControls.HyperLink

        '''<summary>
        '''litPopupStart control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPopupStart As Global.System.Web.UI.WebControls.Literal

        '''<summary>
        '''dgEmoticon control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dgEmoticon As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''litPopupEnd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents litPopupEnd As Global.System.Web.UI.WebControls.Literal
    End Class
End Namespace
