'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.MCP

	Partial Public Class ReportedPost

		'''<summary>
		'''pnlReportedPost control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlReportedPost As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''dgReportedPost control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dgReportedPost As Global.System.Web.UI.WebControls.DataGrid

		'''<summary>
		'''BottomPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents BottomPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''pnlPostDetails control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlPostDetails As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''dgPostReportDetails control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dgPostReportDetails As Global.System.Web.UI.WebControls.DataGrid

		'''<summary>
		'''DetailPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents DetailPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''pnlNoItems control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents pnlNoItems As Global.System.Web.UI.WebControls.Panel

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''lblNoResults control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblNoResults As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
