'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.UCP

	Partial Public Class Profile

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plUserID control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserID As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtUserID control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtUserID As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''plUserName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plUserName As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lblUserName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUserName As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plDisplayName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plDisplayName As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''lblDisplayName control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblDisplayName As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEmail As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmail As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkDisplayEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkDisplayEmail As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''hlEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents hlEmail As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''visEmail control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents visEmail As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plEnableProfileWeb control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableProfileWeb As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableProfileWeb control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableProfileWeb As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''lblWebsite control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblWebsite As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''visWebsite control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents visWebsite As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plEnableProfileRegion control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableProfileRegion As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableProfileRegion control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableProfileRegion As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''lblRegion control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblRegion As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''visRegion control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents visRegion As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rowBio control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowBio As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plBiography control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plBiography As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtBiography control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtBiography As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''tblAdmin control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblAdmin As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''plIsTrusted control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plIsTrusted As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkIsTrusted control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkIsTrusted As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''plLockTrust control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plLockTrust As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkLockTrust control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkLockTrust As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowUserBanning control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowUserBanning As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plIsBanned control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plIsBanned As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkIsBanned control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkIsBanned As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowLiftBanDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowLiftBanDate As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plLiftBanDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plLiftBanDate As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtLiftBanDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtLiftBanDate As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''cmdCalBanDate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdCalBanDate As Global.System.Web.UI.WebControls.HyperLink

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
