'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3074
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.UCP

	Partial Public Class Tracking

		'''<summary>
		'''lblForumTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblForumTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''cmdForum control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdForum As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdThread control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdThread As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''tblForum control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblForum As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''lblForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblForums As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''dgForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dgForums As Global.System.Web.UI.WebControls.DataGrid

		'''<summary>
		'''ForumPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ForumPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''cmdForumRemove control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdForumRemove As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''tblThread control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents tblThread As Global.System.Web.UI.HtmlControls.HtmlTable

		'''<summary>
		'''lblThreads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblThreads As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''dgThreads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dgThreads As Global.System.Web.UI.WebControls.DataGrid

		'''<summary>
		'''ThreadPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ThreadPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''cmdThreadRemove control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdThreadRemove As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
