'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.UCP

	Partial Public Class Signature

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plSignature control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plSignature As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtSignature control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtSignature As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''lblSignature control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblSignature As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''btnPreview control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents btnPreview As Global.System.Web.UI.WebControls.ImageButton

		'''<summary>
		'''btnEdit control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.ImageButton

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
