'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.UCP

    Partial Public Class Tracking

        '''<summary>
        '''lblForumTitle control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblForumTitle As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''rtsNotifications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rtsNotifications As Global.DotNetNuke.Web.UI.WebControls.DnnTabStrip

        '''<summary>
        '''rmpNotifications control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rmpNotifications As Global.DotNetNuke.Web.UI.WebControls.DnnMultiPage

        '''<summary>
        '''rpvForums control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvForums As Global.DotNetNuke.Wrapper.UI.WebControls.DnnPageView

        '''<summary>
        '''gridForumTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridForumTracking As Global.DotNetNuke.Web.UI.WebControls.DnnGrid

        '''<summary>
        '''rpvThreads control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rpvThreads As Global.DotNetNuke.Wrapper.UI.WebControls.DnnPageView

        '''<summary>
        '''gridThreadTracking control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridThreadTracking As Global.DotNetNuke.Web.UI.WebControls.DnnGrid
    End Class
End Namespace
