'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace DotNetNuke.Modules.Forum.UCP

	Partial Public Class Tracking

		'''<summary>
		'''lblForumTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblForumTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''rtsNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rtsNotifications As Global.Telerik.Web.UI.RadTabStrip

		'''<summary>
		'''rmpNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rmpNotifications As Global.Telerik.Web.UI.RadMultiPage

		'''<summary>
		'''rpvForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rpvForums As Global.Telerik.Web.UI.RadPageView

		'''<summary>
		'''lblForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblForums As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''dgForums control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dgForums As Global.System.Web.UI.WebControls.DataGrid

		'''<summary>
		'''ForumPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ForumPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''cmdForumRemove control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdForumRemove As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''rpvThreads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rpvThreads As Global.Telerik.Web.UI.RadPageView

		'''<summary>
		'''lblThreads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblThreads As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''dgThreads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents dgThreads As Global.System.Web.UI.WebControls.DataGrid

		'''<summary>
		'''ThreadPager control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ThreadPager As Global.DotNetNuke.Modules.Forum.WebControls.AjaxPager

		'''<summary>
		'''cmdThreadRemove control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdThreadRemove As Global.System.Web.UI.WebControls.LinkButton
	End Class
End Namespace
