'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DotNetNuke.Modules.Forum.UCP

	Partial Public Class Settings

		'''<summary>
		'''lblTitle control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblTitle As Global.System.Web.UI.WebControls.Label

		'''<summary>
		'''plEmailFormat control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEmailFormat As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''ddlEmailFormat control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents ddlEmailFormat As Global.System.Web.UI.WebControls.DropDownList

		'''<summary>
		'''plThreadsPerPage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plThreadsPerPage As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtThreadsPerPage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtThreadsPerPage As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''Regularexpressionvalidator1 control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents Regularexpressionvalidator1 As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''plPostsPerPage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plPostsPerPage As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''txtPostsPerPage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents txtPostsPerPage As Global.System.Web.UI.WebControls.TextBox

		'''<summary>
		'''valPostsPerPage control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents valPostsPerPage As Global.System.Web.UI.WebControls.RegularExpressionValidator

		'''<summary>
		'''rowOnlineStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowOnlineStatus As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plOnlineStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plOnlineStatus As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkOnlineStatus control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkOnlineStatus As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowMemberList control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowMemberList As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnableMemberList control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableMemberList As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableMemberList control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableMemberList As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEnablePM control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEnablePM As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnablePM control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnablePM As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnablePM control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnablePM As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEnableDefaultPostNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEnableDefaultPostNotify As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnableDefaultPostNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableDefaultPostNotify As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableDefaultPostNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableDefaultPostNotify As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowEnableSelfNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowEnableSelfNotifications As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnableSelfNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableSelfNotifications As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableSelfNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableSelfNotifications As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowPMNotification control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowPMNotification As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnablePMNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnablePMNotifications As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnablePMNotifications control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnablePMNotifications As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''rowForumModNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents rowForumModNotify As Global.System.Web.UI.HtmlControls.HtmlTableRow

		'''<summary>
		'''plEnableForumModNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plEnableForumModNotify As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''chkEnableForumModNotify control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents chkEnableForumModNotify As Global.System.Web.UI.WebControls.CheckBox

		'''<summary>
		'''plClearReads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents plClearReads As Global.DotNetNuke.UI.UserControls.LabelControl

		'''<summary>
		'''cmdClearReads control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdClearReads As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''cmdUpdate control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents cmdUpdate As Global.System.Web.UI.WebControls.LinkButton

		'''<summary>
		'''lblUpdateDone control.
		'''</summary>
		'''<remarks>
		'''Auto-generated field.
		'''To modify move field declaration from designer file to code-behind file.
		'''</remarks>
		Protected WithEvents lblUpdateDone As Global.System.Web.UI.WebControls.Label
	End Class
End Namespace
